[workspace]

members = [
    "casper-civic-verifier",
    "casper-private-auction-core",
    "casper-private-auction-dutch",
    "casper-private-auction-english",
    "casper-private-auction-installer",
    "tests"
]

[profile.release]
lto = true
